# Generated by Django 4.2.11 on 2026-05-28 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('factor_value', models.FloatField(help_text='kgCO2e per unit')),
                ('unit', models.CharField(choices=[('kg_co2e_per_liter', 'kgCO2e / litre'), ('kg_co2e_per_kwh', 'kgCO2e / kWh'), ('kg_co2e_per_km', 'kgCO2e / km'), ('kg_co2e_per_kg', 'kgCO2e / kg'), ('kg_co2e_per_night', 'kgCO2e / hotel night')], max_length=40)),
                ('source', models.CharField(default='DEFRA 2023', max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('auditor', 'Auditor (read-only)')], default='analyst', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ingestion.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_flat_file', 'SAP Flat File (IDoc/CSV)'), ('utility_csv', 'Utility Portal CSV'), ('travel_api', 'Corporate Travel (Concur/Navan JSON)')], max_length=30)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_ok', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('grid_emission_factor', models.FloatField(blank=True, help_text='kgCO2e per kWh — regional electricity grid factor', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='ingestion.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_id', models.CharField(blank=True, help_text='Original row identifier from source system (SAP doc number, utility meter ID, travel booking ref)', max_length=100)),
                ('category', models.CharField(choices=[('fuel_diesel', 'Fuel — Diesel'), ('fuel_petrol', 'Fuel — Petrol'), ('fuel_natural_gas', 'Fuel — Natural Gas'), ('fuel_lpg', 'Fuel — LPG'), ('electricity', 'Electricity'), ('travel_flight_domestic', 'Travel — Flight (Domestic)'), ('travel_flight_short_haul', 'Travel — Flight (Short-haul)'), ('travel_flight_long_haul', 'Travel — Flight (Long-haul)'), ('travel_hotel', 'Travel — Hotel'), ('travel_ground_taxi', 'Travel — Ground (Taxi/Rideshare)'), ('travel_ground_rail', 'Travel — Ground (Rail)'), ('procurement_goods', 'Procurement — Goods'), ('procurement_services', 'Procurement — Services')], max_length=40)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 — Direct'), ('scope2_location', 'Scope 2 — Location-based'), ('scope2_market', 'Scope 2 — Market-based'), ('scope3', 'Scope 3 — Value chain')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_raw', models.FloatField(help_text='Original quantity value')),
                ('unit_raw', models.CharField(help_text="Original unit string, e.g. 'L', 'GAL', 'kWh', 'MWh'", max_length=30)),
                ('currency_raw', models.CharField(blank=True, max_length=10)),
                ('cost_raw', models.FloatField(blank=True, null=True)),
                ('amount_liters', models.FloatField(blank=True, help_text='Normalised to litres (fuels)', null=True)),
                ('amount_kwh', models.FloatField(blank=True, help_text='Normalised to kWh (electricity)', null=True)),
                ('amount_km', models.FloatField(blank=True, help_text='Normalised to km (travel distance)', null=True)),
                ('amount_kg', models.FloatField(blank=True, help_text='Normalised to kg (materials)', null=True)),
                ('amount_nights', models.FloatField(blank=True, help_text='Hotel nights', null=True)),
                ('co2e_kg', models.FloatField(blank=True, help_text='Final computed kgCO2e', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Source-specific fields: SAP plant/material codes, flight origin/dest, meter IDs, etc.')),
                ('is_anomalous', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged — Needs Attention'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False, help_text='True if any field was manually edited post-ingest')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(help_text='Which ingestion batch produced this row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.ingestionbatch')),
                ('emission_factor_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.facilityplant')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_e_tenant__281016_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_e_tenant__87a790_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='ingestion_e_tenant__13d085_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='ingestion_e_batch_i_e7d0fe_idx'),
        ),
    ]
