[build]
  base = "frontend"
  command = "npm install && chmod +x node_modules/.bin/react-scripts && CI= npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200